# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://renjiyun.github.io/explore_nbdev/"

git_url = "https://github.com/renjiyun/explore_nbdev/tree/master/"

def custom_doc_links(name): return None
